import type { Task } from "@/types/task"

export function generateSampleConstructionPlan(): Task[] {
  const baseDate = new Date()
  baseDate.setDate(baseDate.getDate() + 7) // Start next week

  const tasks: Task[] = [
    {
      id: "1",
      taskName: "Site Survey & Preparation",
      duration: 3,
      dependency: null,
      costEstimate: 15000,
      resourceRequired: "Survey crew, 2 laborers",
      weatherSensitive: true,
      startDate: formatDate(baseDate),
      deadline: formatDate(addDays(baseDate, 3)),
      taskCategory: "Structural",
      location: "Entire Site",
      priorityLevel: "High",
      riskLevel: "Low",
      status: "Not Started",
      assignedTeam: "Site Prep Contractors",
      progressPercent: 0,
      slackTime: 1,
      replanAllowed: true,
      equipmentNeeded: "Surveying equipment, bulldozer",
      materialDependencies: "Survey permits, site access",
      costType: "Fixed",
      contingencyBuffer: 10,
      cognitiveTags: ["safety-critical", "deadline-driven"],
      explainabilityNote: "Critical first step - all subsequent work depends on proper site preparation",
      materialBatch: "SURVEY-001",
      crewRole: "Site Preparation",
      shiftRequirement: 1,
      subcontractor: "Precision Survey Co.",
    },
    {
      id: "2",
      taskName: "Foundation Excavation",
      duration: 5,
      dependency: "1",
      costEstimate: 35000,
      resourceRequired: "Excavator operator, 4 laborers",
      weatherSensitive: true,
      startDate: formatDate(addDays(baseDate, 4)),
      deadline: formatDate(addDays(baseDate, 9)),
      taskCategory: "Structural",
      location: "Foundation Area",
      priorityLevel: "High",
      riskLevel: "Medium",
      status: "Not Started",
      assignedTeam: "Ground Works Ltd",
      progressPercent: 0,
      slackTime: 2,
      replanAllowed: true,
      equipmentNeeded: "CAT 320 Excavator, dump trucks",
      materialDependencies: "Soil analysis report",
      costType: "Labor",
      contingencyBuffer: 15,
      cognitiveTags: ["safety-critical", "weather-blocked"],
      explainabilityNote: "Weather-dependent excavation work - cannot proceed in heavy rain",
      materialBatch: "EXCAV-002",
      crewRole: "Heavy Equipment",
      shiftRequirement: 1,
      subcontractor: "Ground Works Ltd",
    },
    {
      id: "3",
      taskName: "Rebar Installation",
      duration: 4,
      dependency: "2",
      costEstimate: 28000,
      resourceRequired: "Rebar crew, 6 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 10)),
      deadline: formatDate(addDays(baseDate, 14)),
      taskCategory: "Structural",
      location: "Foundation Area",
      priorityLevel: "High",
      riskLevel: "Medium",
      status: "Not Started",
      assignedTeam: "Steel Reinforcement Inc",
      progressPercent: 0,
      slackTime: 1,
      replanAllowed: false,
      equipmentNeeded: "Rebar bender, cutting tools",
      materialDependencies: "Rebar delivery batch #R-2024-001",
      costType: "Material",
      contingencyBuffer: 5,
      cognitiveTags: ["safety-critical"],
      explainabilityNote: "Precision work requiring experienced rebar crew",
      materialBatch: "REBAR-R-2024-001",
      crewRole: "Structural Steel",
      shiftRequirement: 1,
      subcontractor: "Steel Reinforcement Inc",
    },
    {
      id: "4",
      taskName: "Concrete Foundation Pour",
      duration: 2,
      dependency: "3",
      costEstimate: 45000,
      resourceRequired: "Concrete crew, 8 workers",
      weatherSensitive: true,
      startDate: formatDate(addDays(baseDate, 15)),
      deadline: formatDate(addDays(baseDate, 17)),
      taskCategory: "Structural",
      location: "Foundation Area",
      priorityLevel: "High",
      riskLevel: "High",
      status: "Not Started",
      assignedTeam: "Concrete Solutions Inc",
      progressPercent: 0,
      slackTime: 0,
      replanAllowed: false,
      equipmentNeeded: "Concrete pump, vibrators, finishing tools",
      materialDependencies: "Concrete batch #C-2024-015",
      costType: "Material",
      contingencyBuffer: 8,
      cognitiveTags: ["safety-critical", "weather-blocked", "deadline-driven"],
      explainabilityNote: "Time-critical pour - concrete must be placed within delivery window",
      materialBatch: "CONCRETE-C-2024-015",
      crewRole: "Concrete",
      shiftRequirement: 2,
      subcontractor: "Concrete Solutions Inc",
    },
    {
      id: "5",
      taskName: "Foundation Curing & Inspection",
      duration: 7,
      dependency: "4",
      costEstimate: 8000,
      resourceRequired: "Inspector, 1 laborer",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 18)),
      deadline: formatDate(addDays(baseDate, 25)),
      taskCategory: "Inspection",
      location: "Foundation Area",
      priorityLevel: "Medium",
      riskLevel: "Low",
      status: "Not Started",
      assignedTeam: "Quality Assurance Team",
      progressPercent: 0,
      slackTime: 3,
      replanAllowed: true,
      equipmentNeeded: "Testing equipment",
      materialDependencies: "Curing compounds",
      costType: "Fixed",
      contingencyBuffer: 5,
      cognitiveTags: ["safety-critical"],
      explainabilityNote: "Mandatory curing period for concrete strength development",
      materialBatch: "CURE-001",
      crewRole: "Quality Control",
      shiftRequirement: 1,
      subcontractor: "QA Inspections LLC",
    },
    {
      id: "6",
      taskName: "Structural Steel Erection",
      duration: 8,
      dependency: "5",
      costEstimate: 85000,
      resourceRequired: "Steel crew, crane operator, 10 workers",
      weatherSensitive: true,
      startDate: formatDate(addDays(baseDate, 26)),
      deadline: formatDate(addDays(baseDate, 34)),
      taskCategory: "Structural",
      location: "Building Frame",
      priorityLevel: "High",
      riskLevel: "High",
      status: "Not Started",
      assignedTeam: "Structural Steel Contractors",
      progressPercent: 0,
      slackTime: 2,
      replanAllowed: true,
      equipmentNeeded: "Tower crane, welding equipment",
      materialDependencies: "Steel beam delivery batch #S-2024-008",
      costType: "Material",
      contingencyBuffer: 12,
      cognitiveTags: ["safety-critical", "weather-blocked"],
      explainabilityNote: "High-risk work requiring crane operations - weather dependent",
      materialBatch: "STEEL-S-2024-008",
      crewRole: "Structural Steel",
      shiftRequirement: 1,
      subcontractor: "Structural Steel Contractors",
    },
    {
      id: "7",
      taskName: "Electrical Rough-in",
      duration: 6,
      dependency: "6",
      costEstimate: 32000,
      resourceRequired: "Electricians, 4 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 35)),
      deadline: formatDate(addDays(baseDate, 41)),
      taskCategory: "Electrical",
      location: "All Floors",
      priorityLevel: "Medium",
      riskLevel: "Medium",
      status: "Not Started",
      assignedTeam: "Metro Electric Co",
      progressPercent: 0,
      slackTime: 4,
      replanAllowed: true,
      equipmentNeeded: "Electrical tools, conduit bender",
      materialDependencies: "Electrical materials batch #E-2024-012",
      costType: "Labor",
      contingencyBuffer: 10,
      cognitiveTags: ["deadline-driven"],
      explainabilityNote: "Must coordinate with other trades for optimal workflow",
      materialBatch: "ELEC-E-2024-012",
      crewRole: "Electrical",
      shiftRequirement: 1,
      subcontractor: "Metro Electric Co",
    },
    {
      id: "8",
      taskName: "Plumbing Rough-in",
      duration: 5,
      dependency: "6",
      costEstimate: 28000,
      resourceRequired: "Plumbers, 3 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 35)),
      deadline: formatDate(addDays(baseDate, 40)),
      taskCategory: "Structural",
      location: "All Floors",
      priorityLevel: "Medium",
      riskLevel: "Medium",
      status: "Not Started",
      assignedTeam: "Reliable Plumbing Services",
      progressPercent: 0,
      slackTime: 3,
      replanAllowed: true,
      equipmentNeeded: "Pipe threading machine, welding torch",
      materialDependencies: "Plumbing materials batch #P-2024-009",
      costType: "Material",
      contingencyBuffer: 8,
      cognitiveTags: [],
      explainabilityNote: "Can run parallel with electrical work to save time",
      materialBatch: "PLUMB-P-2024-009",
      crewRole: "Plumbing",
      shiftRequirement: 1,
      subcontractor: "Reliable Plumbing Services",
    },
    {
      id: "9",
      taskName: "HVAC Installation",
      duration: 7,
      dependency: "7",
      costEstimate: 55000,
      resourceRequired: "HVAC technicians, 5 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 42)),
      deadline: formatDate(addDays(baseDate, 49)),
      taskCategory: "Electrical",
      location: "All Floors",
      priorityLevel: "Medium",
      riskLevel: "Medium",
      status: "Not Started",
      assignedTeam: "Climate Control Systems",
      progressPercent: 0,
      slackTime: 2,
      replanAllowed: true,
      equipmentNeeded: "Ductwork tools, refrigeration equipment",
      materialDependencies: "HVAC equipment batch #H-2024-005",
      costType: "Material",
      contingencyBuffer: 15,
      cognitiveTags: [],
      explainabilityNote: "Complex system requiring specialized technicians",
      materialBatch: "HVAC-H-2024-005",
      crewRole: "HVAC",
      shiftRequirement: 1,
      subcontractor: "Climate Control Systems",
    },
    {
      id: "10",
      taskName: "Drywall Installation",
      duration: 8,
      dependency: "9",
      costEstimate: 38000,
      resourceRequired: "Drywall crew, 6 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 50)),
      deadline: formatDate(addDays(baseDate, 58)),
      taskCategory: "Finishing",
      location: "All Interior Walls",
      priorityLevel: "Medium",
      riskLevel: "Low",
      status: "Not Started",
      assignedTeam: "Perfect Walls Inc",
      progressPercent: 0,
      slackTime: 5,
      replanAllowed: true,
      equipmentNeeded: "Drywall lift, taping tools",
      materialDependencies: "Drywall sheets batch #D-2024-018",
      costType: "Material",
      contingencyBuffer: 7,
      cognitiveTags: [],
      explainabilityNote: "Standard finishing work - good buffer time available",
      materialBatch: "DRYWALL-D-2024-018",
      crewRole: "Drywall",
      shiftRequirement: 1,
      subcontractor: "Perfect Walls Inc",
    },
    {
      id: "11",
      taskName: "Interior Painting",
      duration: 6,
      dependency: "10",
      costEstimate: 25000,
      resourceRequired: "Painters, 4 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 59)),
      deadline: formatDate(addDays(baseDate, 65)),
      taskCategory: "Finishing",
      location: "All Interior Spaces",
      priorityLevel: "Low",
      riskLevel: "Low",
      status: "Not Started",
      assignedTeam: "Professional Painters Co",
      progressPercent: 0,
      slackTime: 7,
      replanAllowed: true,
      equipmentNeeded: "Spray equipment, brushes, rollers",
      materialDependencies: "Paint batch #PT-2024-022",
      costType: "Material",
      contingencyBuffer: 5,
      cognitiveTags: [],
      explainabilityNote: "Final finishing work with flexible scheduling",
      materialBatch: "PAINT-PT-2024-022",
      crewRole: "Painting",
      shiftRequirement: 1,
      subcontractor: "Professional Painters Co",
    },
    {
      id: "12",
      taskName: "Flooring Installation",
      duration: 5,
      dependency: "11",
      costEstimate: 42000,
      resourceRequired: "Flooring crew, 4 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 66)),
      deadline: formatDate(addDays(baseDate, 71)),
      taskCategory: "Finishing",
      location: "All Floor Areas",
      priorityLevel: "Medium",
      riskLevel: "Low",
      status: "Not Started",
      assignedTeam: "Premium Flooring Solutions",
      progressPercent: 0,
      slackTime: 3,
      replanAllowed: true,
      equipmentNeeded: "Floor sanders, installation tools",
      materialDependencies: "Flooring materials batch #F-2024-011",
      costType: "Material",
      contingencyBuffer: 8,
      cognitiveTags: [],
      explainabilityNote: "High-quality flooring requiring careful installation",
      materialBatch: "FLOOR-F-2024-011",
      crewRole: "Flooring",
      shiftRequirement: 1,
      subcontractor: "Premium Flooring Solutions",
    },
    {
      id: "13",
      taskName: "Final Electrical & Fixtures",
      duration: 4,
      dependency: "12",
      costEstimate: 22000,
      resourceRequired: "Electricians, 3 workers",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 72)),
      deadline: formatDate(addDays(baseDate, 76)),
      taskCategory: "Electrical",
      location: "All Areas",
      priorityLevel: "Medium",
      riskLevel: "Low",
      status: "Not Started",
      assignedTeam: "Metro Electric Co",
      progressPercent: 0,
      slackTime: 2,
      replanAllowed: true,
      equipmentNeeded: "Electrical testing equipment",
      materialDependencies: "Light fixtures batch #LF-2024-007",
      costType: "Material",
      contingencyBuffer: 5,
      cognitiveTags: [],
      explainabilityNote: "Final electrical connections and testing",
      materialBatch: "FIXTURES-LF-2024-007",
      crewRole: "Electrical",
      shiftRequirement: 1,
      subcontractor: "Metro Electric Co",
    },
    {
      id: "14",
      taskName: "Final Inspection & Handover",
      duration: 3,
      dependency: "13",
      costEstimate: 12000,
      resourceRequired: "Inspector, project manager",
      weatherSensitive: false,
      startDate: formatDate(addDays(baseDate, 77)),
      deadline: formatDate(addDays(baseDate, 80)),
      taskCategory: "Inspection",
      location: "Entire Project",
      priorityLevel: "High",
      riskLevel: "Medium",
      status: "Not Started",
      assignedTeam: "Project Management Office",
      progressPercent: 0,
      slackTime: 1,
      replanAllowed: false,
      equipmentNeeded: "Inspection tools, documentation",
      materialDependencies: "Completion certificates",
      costType: "Fixed",
      contingencyBuffer: 3,
      cognitiveTags: ["deadline-driven", "safety-critical"],
      explainabilityNote: "Critical final step - project completion depends on passing inspection",
      materialBatch: "INSPECT-FINAL",
      crewRole: "Management",
      shiftRequirement: 1,
      subcontractor: "Internal Team",
    },
  ]

  return tasks
}

function formatDate(date: Date): string {
  return date.toISOString().split("T")[0]
}

function addDays(date: Date, days: number): Date {
  const result = new Date(date)
  result.setDate(result.getDate() + days)
  return result
}
